os: linux

services:
  - docker

language: go

go:
  - "1.13"
  - "1.14"
  - "1.15"
  - master

branches:
  only:
  - master

script:
  - go test -race -v ./examples/pipe/...
  - go test -race -v ./examples/serial/...
  - go test -race -v ./examples/udprx/...
  - go test -race -v ./mavlink/...
  - go test -race -v ./mavgen/...

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build . -t $DOCKER_USERNAME/$DOCKER_REPO

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/$DOCKER_REPO

