os: linux

services:
  - docker

language: go

script:
  - go test -race -v ./examples/udprx/...
  - go test -race -v ./examples/mavlink1/...
  - go test -race -v ./examples/mavlink2/...
  - go test -race -v ./mavgen/...

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build . -t $DOCKER_USERNAME/$DOCKER_REPO

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/$DOCKER_REPO
  on:
    branch: master

