
language: go

go:
  - "1.12.9"

# run mavgen on the mavlink package, and run tests

script:
  - go test -race -v ./examples/udprx/...
  - go test -race -v ./examples/mavlink1/...
  - go test -race -v ./examples/mavlink2/...
  - go test -race -v ./mavgen/...
