sudo: required

services:
  - docker

language: go

test:
  provider: script
  script:
    - go test -race -v ./examples/udprx/...
    - go test -race -v ./examples/mavlink1/...
    - go test -race -v ./examples/mavlink2/...
    - go test -race -v ./mavgen/...
  on:
    branch: master

deploy:
  provider: script
  script: 
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build . -t $DOCKER_USERNAME/$DOCKER_REPO
    - docker push $DOCKER_USERNAME/$DOCKER_REPO
  on:
    branch: master

