
language: go

go:
  - 1.12.9

# run mavgen on the mavlink package, and run tests

script:
  - go generate github.com/asmyasnikov/go-mavlink/examples/mavlink1
  - go generate github.com/asmyasnikov/go-mavlink/examples/mavlink1
  - go generate github.com/asmyasnikov/go-mavlink/examples/mavlink1
  - go test -race -v ./...
